NumPy Exercises for Data Analysis

In [ ]:
# 1. Import numpy as np and see the version

import numpy as np

print(np.__version__)
pass

1.22.4


In [ ]:
# 2. Create a 1D array of numbers from 0 to 9
# your code here
pass

In [ ]:
# 3. Create a 3×3 numpy array of all True’s
arr = np.ones((3, 3), dtype=bool)
print(arr)
pass

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# 4. Extract all odd numbers from arr
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
odd_nums = arr[arr % 2 == 1]
print(odd_nums)
pass

[1 3 5 7 9]


In [ ]:
# 5. Replace all odd numbers in arr with -1
mask = arr % 2 == 1
arr[mask] = -1
print(arr)
pass

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [ ]:
#  6. Convert a 1D array to a 2D array with 2 rows
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, -1)
print(new_arr)
pass

[[1 2 3]
 [4 5 6]]


In [ ]:
#  7. Stack arrays a and b vertically
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.vstack((a, b))
print(c)
pass

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#  8. Stack the arrays a and b horizontally.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.hstack((a, b))
print(c)
pass

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#  9. Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
mask = (a >= 5) & (a <= 10)
result = a[mask]

print(result)
import numpy as np
a = np.arange(15)
# pass

[ 6  9 10]


In [ ]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here

def my_func(x):
    return x ** 2 + 1
    my_func_vec = np.vectorize(my_func)
    arr = np.array([5, 7, 9, 8, 6, 4, 5])
    arr = np.array([6, 3, 4, 8, 9, 7, 1])
    pair_max(a, b)
    result = my_func_vec(arr)

print(result)
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)


[ 6  9 10]


5

In [ ]:
#  11. Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
arr = np.array([[0, 2, 1], [3, 5, 4], [6, 8, 7]])
arr[:, [1, 0, 2]] = arr[:, [0, 1, 2]]
pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

arr = np.random.uniform(low=5, high=10, size=(5,3))

print(arr)

[[6.50288792 8.22029802 5.36766788]
 [9.16155137 8.31131619 8.50574495]
 [7.53966445 8.03151441 6.21299538]
 [9.50225979 9.28089916 8.59176978]
 [9.33437711 9.34242831 7.11835439]]
